### ISSUE TITLE
Obrigado

### ISSUE THREAD

**Issue by romanoh** [gsavio/player-shoutcast-html5#1]
Muito bom, pode aparecer o nome do Album?
Obrigado pelo seu trabalho.

edit: a melhor maneira de meter é usando: 

`<?php` include 'player/index.html'; ?>

é que não me esta a resultar.
[https://i.imgur.com/eNvhwzT.png](url)

**Comment by gsavio** [comment]
É possível exibir o nome do album se esta informação estiver no API do iTunes. Basta retornar ela do json que é retornado, como por exemplo:

Adicione esta linha no arquivo *scripts.js* na pasta *js*, após a linha 150 e irá te retornar um alerta com o nome do album.
```javascript
alert(dados.results[0].collectionCensoredName)
```
Após isso, basta exibir a informação do jeito que você preferir.

Quanto ao não conseguir incluir o player, ao dar o include os arquivos CSS e JS estão sendo chamados?

Estou à disposição para ajudar.

**Comment by romanoh** [comment]
Vou fazer como disse.

Entretanto meti o teu script a funcionar e afinal aparece o nome do album mas o nome da musica não aparece.

[http://morrisseyradio.com/player/index.html#](url)

**Comment by gsavio** [comment]
Pelo que eu vi, seu streaming exibe 3 informações sobre a música atual. Vejo duas possibilidade para resolver seu problema:

1 - Você pode alterar os arquivos de seu streaming para exibir "artista - música" e pegar o album através do API do iTunes, se estiver disponível a informação;

2 - Alterar o arquivo que pega os dados de seu servidor, o **dados.php**, por exemplo, após a linha 129 poderia adicionar algo como:
```php
$array['test'] = trim(substr($faixaAtual[2], 0, -14));
```
Isso fará com que mostre todas as informações da música atual que é exibida em seu streaming e que são separadas por hifens.

Não se esqueça de alterar no arquivo **script.js** a constante DEMO para false.
