### ISSUE TITLE
como fazer para que o nextsong funcione?

### ISSUE THREAD

**Issue by FabioTech** [gsavio/player-shoutcast-html5#10]
olá eu tentei fazer com que o nextsong funcionasse mas não conseguir. tem como vc me ajudar?

**testei isso:**
$nextSong = filter_input(INPUT_GET, 'next', FILTER_VALIDATE_BOOLEAN);
if(!empty($url)) {
	if($historic) {
		$urls[] = $url . '/7.html';
		$urls[] = $url . '/played';
		if($nextSong) $urls[] = $url . '/nextsong';
		
		$curl = curl_multi_init();
		foreach($urls as $key => $value){
			$ch[$key] = curl_init($value);
			curl_setopt($ch[$key], CURLOPT_RETURNTRANSFER, true);
			curl_setopt($ch[$key], CURLOPT_USERAGENT, 'Mozilla/5.0');
			curl_multi_add_handle($curl, $ch[$key]);
		}
		
		do {
		curl_multi_exec($curl, $running);
		curl_multi_select($curl);
		} while ($running > 0);
		
		foreach(array_keys($ch) as $key){
			curl_multi_remove_handle($curl, $ch[$key]);
			$content[] = curl_multi_getcontent($ch[$key]);
		}

		$data = $content[0];

		if($nextSong) {
			$nextSongName = (isset($content[2])) ? explode('-', $content[2]) : '';

			if(isset($nextSongName[1])) {
				$array['nextSong'] = ['artist' => $nextSongName[0], 'song' => $nextSongName[1]];
			} else {
				$array['nextSong'] = ['artist' => '', 'song' => $nextSongName[0]];
			}
		}

		// Put the songs name between <music> tag
		$pagina = str_replace('</td><td>', '<music>', $content[1], $count);

		$playedSongs = explode('<music>', $pagina);

		// Remove unrelacionated content
		unset($playedSongs[0]);
		unset($playedSongs[1]);
		unset($playedSongs[2]);

		foreach($playedSongs as $song) {
			// Get the name of the song
			$cutStr = strpos($song, '</td></tr>');
			$playedSong = substr($song, 0, $cutStr);
			
			// Separate artist from song
			$songData = explode('-', $playedSong);
			$songNameHistoric = (!empty($songData[1])) ? trim($songData[1]) : '';
			
			// Put in the principal array
			$array['songHistory'][] = ['artist' => rtrim($songData[0]), 'song' => $songNameHistoric];
		}
		
		curl_multi_close($curl);
	} else {
		$curl = curl_init($url . '/7.html');

		curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0');
		
		$data = curl_exec($curl);
		
		curl_close($curl);
	}

**e mais isso:**

const next = true;

    this.refreshHistoric = function (info, n) {
        var $nextDiv = document.querySelectorAll('#nextSong article');
        var $songName = document.querySelectorAll('#nextSong article .music-info .song');
        var $artistName = document.querySelectorAll('#nextSong article .music-info .artist');

        // Default cover art
        var urlCoverArt = 'img/bg-capa.jpg';

        // Get cover art for song history
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                var data = JSON.parse(this.responseText);
                var artworkUrl100 = (data.resultCount) ? data.results[0].artworkUrl100 : urlCoverArt;

                document.querySelectorAll('#nextSong article .cover-historic')[n].style.backgroundImage = 'url(' + artworkUrl100 + ')';
            }
            // Formating characters to UTF-8
            var music = info.song.replace(/&apos;/g, '\'');
            var songHist = music.replace(/&amp;/g, '&');

            var artist = info.artist.replace(/&apos;/g, '\'');
            var artistHist = artist.replace(/&amp;/g, '&');

            $songName[n].innerHTML = songHist;
            $artistName[n].innerHTML = artistHist;

            // Add class for animation
            $nextDiv[n].classList.add('animated');
            $nextDiv[n].classList.add('slideInRight');
        }
        xhttp.open('GET', 'https://itunes.apple.com/search?term=' + info.artist + ' ' + info.song + '&media=music&limit=1', true);
        xhttp.send();

        setTimeout(function () {
            for (var j = 0; j < 2; j++) {
                $nextDiv[j].classList.remove('animated');
                $nextDiv[j].classList.remove('slideInRight');
            }
        }, 2000);
    }

**tambem mudei aqui e nada:**

    var d = new Date();

    // Requisition with timestamp to prevent cache on mobile devices
    xhttp.open('GET', 'api.php?url=' + URL_STREAMING + '&historic=' + HISTORIC + '&next=' + NEXT + '&t=' + d.getTime(), true);
    xhttp.send();
}

**Comment by gsavio** [comment]
Olá, @FabioTech 

O seu streaming está exibindo esta informação?

**Comment by FabioTech** [comment]
**SIM, VI NO SEU STREAMING:**     

// Requisition with timestamp to prevent cache on mobile devices
    xhttp.open('GET', 'https://noplayermusic.000webhostapp.com/api.php?url=' + URL_STREAMING + '&historic=' + HISTORIC + '&next=' + NEXT + '&t=' + d.getTime(), true);
    xhttp.send();

https://noplayermusic.000webhostapp.com/api.php?url=https://stm6-ssl.painelcast.com:6934&historic=true&nextSong=true&t=1588603094168

// Set NEXTSONG to true to get the last songs played
const NEXT = true;

**QUERO QUE ELE ME RETORNE CAPA DO ÁLBUM E CANTOR DA MUSICA.**

**VI QUE ELE PEGA NOME DA CANÇÃO E CAPA DO ÁLBUM AQUI:**

**QUERO SABER SE TEM COMO ADICIONAR A FUNÇÃO PRA VER A PRÓXIMA CANÇÃO?**

    this.refreshHistoric = function (info, n) {
        var $historicDiv = document.querySelectorAll('#historicSong .box_music');
        var $songName = document.querySelectorAll('#historicSong .box_music .music-info .song');
        var $artistName = document.querySelectorAll('#historicSong .box_music .music-info .artist');

        // Default cover art
        var urlCoverArt = '../img/bg-capa.jpg';

        // Get cover art for song history
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                var data = JSON.parse(this.responseText);
                var artworkUrl100 = (data.resultCount) ? data.results[0].artworkUrl100 : urlCoverArt;

                document.querySelectorAll('#historicSong .box_music .cover-historic')[n].style.backgroundImage = 'url(' + artworkUrl100 + ')';
            }
            // Formating characters to UTF-8
            var music = info.song.replace(/&apos;/g, '\'');
            var songHist = music.replace(/&amp;/g, '&');

            var artist = info.artist.replace(/&apos;/g, '\'');
            var artistHist = artist.replace(/&amp;/g, '&');

            $songName[n].innerHTML = songHist;
            $artistName[n].innerHTML = artistHist;

            // Add class for animation
            $historicDiv[n].classList.add('animated');
            $historicDiv[n].classList.add('slideInRight');
        }
        xhttp.open('GET', 'https://itunes.apple.com/search?term=' + info.artist + ' ' + info.song + '&media=music&limit=1', true);
        xhttp.send();

        setTimeout(function () {
            for (var j = 0; j < 2; j++) {
                $historicDiv[j].classList.remove('animated');
                $historicDiv[j].classList.remove('slideInRight');
            }
        }, 2000);
    }

    this.refreshCover = function (song = '', artist) {
        // Default cover art
        var urlCoverArt = 'img/bg-capa.jpg';

        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            var coverArt = document.getElementById('currentCoverArt');
            var coverBackground = document.getElementById('bgCover');

            // Get cover art URL on iTunes API
            if (this.readyState === 4 && this.status === 200) {
                var data = JSON.parse(this.responseText);
                var artworkUrl100 = (data.resultCount) ? data.results[0].artworkUrl100 : urlCoverArt;

                // Se retornar algum dado, alterar a resolução da imagem ou definir a padrão
                urlCoverArt = (artworkUrl100 != urlCoverArt) ? artworkUrl100.replace('100x100bb', '512x512bb') : urlCoverArt;
                var urlCoverArt96 = (artworkUrl100 != urlCoverArt) ? urlCoverArt.replace('512x512bb', '96x96bb') : urlCoverArt;
                var urlCoverArt128 = (artworkUrl100 != urlCoverArt) ? urlCoverArt.replace('512x512bb', '128x128bb') : urlCoverArt;
                var urlCoverArt192 = (artworkUrl100 != urlCoverArt) ? urlCoverArt.replace('512x512bb', '192x192bb') : urlCoverArt;
                var urlCoverArt256 = (artworkUrl100 != urlCoverArt) ? urlCoverArt.replace('512x512bb', '256x256bb') : urlCoverArt;
                var urlCoverArt384 = (artworkUrl100 != urlCoverArt) ? urlCoverArt.replace('512x512bb', '384x384bb') : urlCoverArt;

                coverArt.style.backgroundImage = 'url(' + urlCoverArt + ')';
                coverArt.className = 'animated bounceInLeft';

                coverBackground.style.backgroundImage = 'url(' + urlCoverArt + ')';

                setTimeout(function () {
                    coverArt.className = '';
                }, 2000);

                if ('mediaSession' in navigator) {
                    navigator.mediaSession.metadata = new MediaMetadata({
                        title: song,
                        artist: artist,
                        artwork: [{
                                src: urlCoverArt96,
                                sizes: '96x96',
                                type: 'image/png'
                            },
                            {
                                src: urlCoverArt128,
                                sizes: '128x128',
                                type: 'image/png'
                            },
                            {
                                src: urlCoverArt192,
                                sizes: '192x192',
                                type: 'image/png'
                            },
                            {
                                src: urlCoverArt256,
                                sizes: '256x256',
                                type: 'image/png'
                            },
                            {
                                src: urlCoverArt384,
                                sizes: '384x384',
                                type: 'image/png'
                            },
                            {
                                src: urlCoverArt,
                                sizes: '512x512',
                                type: 'image/png'
                            }
                        ]
                    });
                }
            }
        }
        xhttp.open('GET', 'https://itunes.apple.com/search?term=' + artist + ' ' + song + '&media=music&limit=1', true);
        xhttp.send();
    }

**Comment by FabioTech** [comment]
> Olá, @FabioTech
> 
> O seu streaming está exibindo esta informação?

**VER COMO EU DEIXEI ELE:** https://i.imgur.com/aam2JvB.png

**Comment by gsavio** [comment]
@FabioTech, clone novamente o projeto e veja se o seu problema foi resolvido.

Desconfio que tenha algo a ver com o ssl no streaming. Adicionei a configuração CURLOPT_SSL_VERIFYPEER nas opções do curl, espero que resolva.

Qualquer dúvida, ajudarei assim que possível. E boa sorte com seu projeto.

**Comment by FabioTech** [comment]
Olha aqui, onde estou testando o seu player, https://noplayer.fabiosakamoto.com/
não estou conseguindo gerar o codigo de proxima musica. como vc fez, vc entende melhor como fazer ele retornar a proxima canção: https://noplayer.fabiosakamoto.com/api.php?url=https://stm6-ssl.painelcast.com:6934&historic=true&next=true&t=1593097280516

**Comment by gsavio** [comment]
@FabioTech, atualize o seu projeto e faça o teste novamente, já pode ter sido corrigido.

Quando fui testar, seu streaming estava offline.

**Comment by FabioTech** [comment]
Reativei tinha desligado sozinho o streaming, dar uma olhada no nextsong: https://noplayer.fabiosakamoto.com/

ele esta dando esse erro:

Uncaught ReferenceError: NEXT is not defined
    at getStreamingData (script.js:385)
    at window.onload (script.js:32)

atualizei, conforme novo modelo que vc postou, vi que tem que ter o codigo de nextsong, no caso um codigo separado para gerar nome da proxima canção e capa do album

**Comment by gsavio** [comment]
Na verdade, passando o parâmetro next como true e sendo um streaming shoutcast que exiba esta informação, ela já deve ser exibida. 

Precisando de alguma ajuda, só avisar. Abraços.

**Comment by FabioTech** [comment]
Vi que no script.js não tem a função que chama para adicionar o código de
next ele só tem "historicsong" que dar o resultado de música anterior

Em seg, 29 de jun de 2020 16:53, Guilherme Sávio <notifications@github.com>
escreveu:

**Comment by FabioTech** [comment]
Vi que no script.js não tem a função que chama para adicionar o código de
next ele só tem "historicsong" que dar o resultado de música anterior .

tem como vc adicionar a função: <div class="row" id="nextSong">

<div class="row historic">
<div class="col-12">
<h2>Recently Played</h2>
<div class="row" id="historicSong">
<article class="col-12 col-md-6">
<div class="cover-historic"></div>
<div class="music-info">
<div class="song">...</div>
<div class="artist">...</div>
</div>
</article>
<article class="col-12 col-md-6">
<div class="cover-historic"></div>
<div class="music-info">
<div class="song">...</div>
<div class="artist">...</div>
</div>
</article>
</div>

Em seg., 29 de jun. de 2020 às 16:56, Fábio Sakamoto <
fabiosakamotoma@gmail.com> escreveu:

**Comment by serrgyo** [comment]
ola viva o que vou postar á frente sei que nao tem nada a ver mas como nao entendo muito de codigos se me poderem ajudar agradecia, com seguinte codigo dá para exebir uma capa mas sai com 100X100 gostava que sai-se 400x400 ou outras medidas 

<html>
    <head>
        <title>album</title>
        <meta http-equiv="refresh" content="30">
    </head>
<body>

<?php

$debug = true;

/* --BEGIN: functions */

function remove_utf8_bom($text)
{
    $bom = pack('H*','EFBBBF');
    $text = preg_replace("/^$bom/", '', $text);
    return $text;
}

function iTunes_get($combine)
{

	$json = file_get_contents('https://itunes.apple.com/search?term=='.$combine.'&media=music&limit=1');
	
	$obj = remove_utf8_bom($json);
		
	$obj=preg_replace('/.+?({.+}).+/','$1',$obj);
	
	$obj=json_decode($obj,TRUE);
	
	return $obj;
}

function clean($in)
{
	// returns cleaned songtitle
	
	$in = preg_replace("/\([^)]+\)/","",$in);  //removed parenthesis
	$in = preg_replace("/\[[^]]+\]/","",$in);  //removed brackets
	
	return(str_ireplace(' -','',$in));
}/* --END: functions */

/*  Get Artist - Song - Server Name */
$server = "http://51.75.145.68:9988/stats?sid=1&json=0&callback=?";

$srv_url = urlencode($server);

$sc_stats = simplexml_load_file($srv_url);

/* gets other information about current track here */

$album = iTunes_get(urlencode(clean($sc_stats->SONGTITLE)));



extract($album);

/* special trickery goes here */

echo "<div><img  src=\"".$album['results'][0]['artworkUrl100']."\"/></div>";

?>
</body></html>

**Comment by serrgyo** [comment]
$debug = true;

/* --BEGIN: functions */

function remove_utf8_bom($text)
{
    $bom = pack('H*','EFBBBF');
    $text = preg_replace("/^$bom/", '', $text);
    return $text;
}

function iTunes_get($combine)
{

	$json = file_get_contents('https://itunes.apple.com/search?term=='.$combine.'&media=music&limit=1');
	
	$obj = remove_utf8_bom($json);
		
	$obj=preg_replace('/.+?({.+}).+/','$1',$obj);
	
	$obj=json_decode($obj,TRUE);
	
	return $obj;
}

function clean($in)
{
	// returns cleaned songtitle
	
	$in = preg_replace("/\([^)]+\)/","",$in);  //removed parenthesis
	$in = preg_replace("/\[[^]]+\]/","",$in);  //removed brackets
	
	return(str_ireplace(' -','',$in));
}/* --END: functions */

/*  Get Artist - Song - Server Name */
$server = "http://51.75.145.68:9988/stats?sid=1&json=0&callback=?";

$srv_url = urlencode($server);

$sc_stats = simplexml_load_file($srv_url);

/* gets other information about current track here */

$album = iTunes_get(urlencode(clean($sc_stats->SONGTITLE)));



extract($album);

/* special trickery goes here */

echo "<div><img  src=\"".$album['results'][0]['artworkUrl100']."\"/></div>";
