### ISSUE TITLE
 Updated code doesn't work

### ISSUE THREAD

**Issue by juanamm** [gsavio/player-shoutcast-html5#13]
As the above code stopped working, I have used the updated one, but it doesn't work.
It doesn't even allow you to connect to the streaming server! 
Now neither old nor new code works :/

**Comment by gsavio** [comment]
Hi @juanamm,

Your api.php file is not bringing any information about any streaming during my tests. Try to update your project and if you still need help, open a new issue and if possible, with more details. Thank you.
