### ISSUE TITLE
Bad division of the string in some songs name - SHOUTcast [Fixed]

### ISSUE THREAD

**Issue by juanamm** [gsavio/player-shoutcast-html5#18]
Suppose the song name contains the character "-".
Example: D.OZi - Ganas de vivir (feat. Ken-Y)

Separating the artist from the song name results:
Artist: D.OZi
Song: Ganas de vivir (feat. Ken

I have fixed it by modifying 3 lines of api.php.

**Original code:**
`$nextSongName = (isset($content[2])) ? explode('-', $content[2]) : '';`
`// Separate artist from song`
`$songData = explode('-', $playedSong);`
`// Separate artist from song`
`$currentSong = explode('-', $playingNow);`

**Modified code:**
`$nextSongName = (isset($content[2])) ? explode('-', $content[2], 2) : '';`
`// Separate artist from song`
`$songData = explode('-', $playedSong, 2);`
`// Separate artist from song`
`$currentSong = explode('-', $playingNow, 2);`

In this way `explode` divides string only at the first occurrence of the character "-".

**Comment by FabioTech** [comment]
https://noplayer.fabiosakamoto.com/
