### ISSUE TITLE
Song info and other details not getting displayed

### ISSUE THREAD

**Issue by adukale** [gsavio/player-shoutcast-html5#19]
Hi

I have installed shoutcast but I am unable to get this player to work, can listen to the stream though.
Link: http://172.105.48.178/play.html

Thank You

**Comment by FabioTech** [comment]
https://noplayer.fabiosakamoto.com/

**Comment by adukale** [comment]
Its not working for me.
I have removed the script from the location but I have tried multiple times and the information is not getting displayed.

**Comment by juanamm** [comment]
> Its not working for me.
> I have removed the script from the location but I have tried multiple times and the information is not getting displayed.

First you have to have HTTPS streaming, then you have to make some modifications to make it work.
[Here](https://github.com/gsavio/player-shoutcast-html5/issues/16#issuecomment-654850117) I have shared some things that I have modified on my own.
I have also shared other tips in the other closed threads, see them to see if they can help you.
Until developer updates the code, that's what I can suggest.
