### ISSUE TITLE
Change cover finder

### ISSUE THREAD

**Issue by jjbiosca** [gsavio/player-shoutcast-html5#20]
Good Morning,
First of all, thank you for this fantastic player. I have been using it for more than a year and it is the best I have had, both in appearance and function.
I would like to know if there is a possibility to change the iTunes cover search engine and to look for the cover in my own folder uploaded to the server. The problem is that the album that is playing is not always well displayed. In this way, it would show the cover that I have saved in that folder.
I have been doing different tests, but not being a programmer I have not been able to achieve it.
Thank you so much for everything.

Buenos días,
Primero darte las gracias por este reproductor fantástico. Llevo más de un año usándolo y es el mejor que he tenido, tanto en apariencia como funcional.
Me gustaría saber si hay posibilidad de cambiar el buscador de carátulas de Itunes y que busque la carátula en mi propia carpeta subida al servidor. El problema es que no siempre se muestra bien la carátula que está sonando. De esta forma, mostraría la caratula que yo he guardado en esa carpeta.
He estado haciendo diferentes pruebas, pero al no ser programador no he sido capaz de conseguirlo.
Muchas gracias por todo.

**Comment by juanamm** [comment]
I don't know if it's a good idea for you to do that task if you know little about programming.
Besides taking up unnecessary space on your server, it can give you headaches.
To get the exact cover of your song in iTunes you have to verify that the tags of your songs are correctly set.
There are many programs for editing tags, for example IDTE - ID3 Tag Editor.
You can also download your favorite songs using Spotify or Deemix that add the tags correctly.
If you see that any image does not match you, do a Google search with the Artist - iTunes song name.

This link will take you to the iTunes database where you can see the artist's name, the song's name, the album's name, duration, etc. and then verify that all that information matches what you have stored in your song.
Example: Aerosmith - Sweet Emotion

![itunes](https://user-images.githubusercontent.com/48572613/90349926-e4728e00-e011-11ea-9001-d1cf278fd18e.png)

You will see that there are many Aerosmith albums that contain that song, depending on whether it is a live version, unplugged, remix, single, etc, if you enter each of those albums you will see all the data that you must have configured in the tags of your songs to Let Itunes show you the cover you want.
Sometimes I have had to insist and look at everything 10 times, including the length of the song, sometimes they do not match and I think that is where the differences come from with the Itunes algorithm.

I hope I've helped.

--------------------------------------------------------

No se si es una buena idea que te pongas en esa tarea si conoces poco de programación.
Además de ocupar espacio innecesario en tu servidor puede darte dolores de cabeza.
Para obtener la caratula exacta de tu canción en Itunes tienes que verificar que los tags de tus canciones estén correctamente configurados.
Existen muchos programas para editar tags, por ejemplo  IDTE - ID3 Tag Editor.
También puedes descargar tus canciones favoritas usando Spotify o Deemix que te agregan los tags correctamente.
Si ves que alguna imagen no te coincide, haz una búsqueda en Google con el Artista - nombre de la canción Itunes.

Ese enlace te llevará a la base de datos de Itunes donde podrás ver el nombre del artista, el nombre de la canción, el nombre del álbum, duración, etc y luego verifica que toda esa información coincida con la que tienes almacenada en tu canción.
Por ejemplo: Aerosmith - Sweet Emotion
Verás que existen muchos álbumes de Aerosmith que contienen esa canción, dependiendo si es una versión live, unplugged, remix, single, etc, si entras en cada uno de esos albumes verás todos los datos que debes tener configurados en los tags de tus canciones para que Itunes te muestre la caratula que deseas.
Algunas veces he tenido que insistir y mirar todo 10 veces, incluida la duración de la canción, unas veces no coinciden y pienso que ahí es donde vienen las diferencias con el algoritmo de Itunes.

Espero haberte ayudado.

**Comment by jjbiosca** [comment]
Thank you very much for answering,

The problem may come due to time, because I always edit the mp3 tags with the Itunes information, but if the song is very quiet at the beginning or end, I also edit it and cut it. I will try to check the weather from now on.

In any case, the idea of uploading the covers to the server is still a good idea, because this way when I put a jingle or another cut, I can change the cover that is shown and that it cannot find in iTunes because it is not a song, and This way I only show the image that is put for when it does not find any.

Thank you very much for your help



Muchas gracias por contestar,

El problema puede venir por el tiempo, porque siempre edito los tag de los mp3 con la información de Itunes, pero si el tema tiene mucho silencio al inicio o al final, también lo edito y lo recorto. Intentaré revisar el tiempo a partir de ahora.

De todas formas, la idea de subir las carátulas al servidor sigue siendo una buena idea, porque así cuando pongo un jingle u otro corte, puedo ir cambiando la carátula que se muestra y que no encuentra en Itunes porque no es ninguna canción, y de esta forma solo muestro la imagen que hay puesta para cuando no encuentra ninguna.

Muchas gracias por tu ayuda

**Comment by hiro-rocks** [comment]
SAM broadcaster is using this method. Every album has every album art was uploaded.

Shoutcast itself doesn't have album info, so pulling from lastfm and itunes is mostly wrong album art

**Comment by juanamm** [comment]
> De todas formas, la idea de subir las carátulas al servidor sigue siendo una buena idea, porque así cuando pongo un jingle u otro corte, puedo ir cambiando la carátula que se muestra y que no encuentra en Itunes porque no es ninguna canción, y de esta forma solo muestro la imagen que hay puesta para cuando no encuentra ninguna.
> 
Bueno como veo que hablas castellano te la voy a facilitar y te resolveré esto de las caratulas para los jingles, tandas o promos.
**Sube a la carpeta /img** del servidor  por ejemplo 3 imágenes, una para jingles, otra para tandas y otra para promos.
Supongamos que el nombre que les pondrás son jingle.jpg, tanda.jpg y promo.jpg
Luego cuando vayas a pasar un jingle, tanda o promo, modifica el tag de la música de fondo que vas a poner en ese momento para que el **artista** sea igual a Jingle, Tanda o Promo respectivamente.

Luego modificaremos el `script.js` para que cambie la imagen por defecto dependiendo del nombre del artista, esto quiere decir que si el corte que estás pasando en ese momento lleva como nombre de artista alguno de los anteriores la imagen por defecto la cambiaremos a otra y si el artista no coincide con ninguno de esos la imagen por defecto será la clásica que hayas definido.

Te la voy hacer fácil, aunque técnicamente no es lo correcto, definiremos 3 constantes con la ruta hacia las imágenes en dos lugares del script, digo que técnicamente no es lo correcto porque sería bueno que estas constantes las definas una sola vez en el `config.js` como tienes todas las demás constantes que van con mayúsculas. Y si las defines ahí, no es necesario que las definas en estos 2 lugares que te indicaré. Esto es solo por un tema de técnica, todo funcionará correctamente en ambos casos.

Ve a la función `this.refreshHistoric = function (info, n) {`
Yo he modificado mucho este script por lo cual el número de la línea quizá no coincida con el tuyo pero no te preocupes que te indicaré exactamente el lugar.
debajo de la 3er línea, o sea, debajo de `var $artistName = document.querySelectorAll('#historicSong article .music-info .artist');`
busca algo que diga:  
```
// Default cover art
var urlCoverArt = DEFAULT_COVER_ART;
```

Eso lo vamos a sustituir por estas líneas:
```
// Default cover art
const JINGLE_COVER_ART = "img/jingle.jpg";
const TANDA_COVER_ART = "img/tanda.jpg";
const PROMO_COVER_ART = "img/promo.jpg";
    	   
var artistRadio = info.artist.replace(/&apos;/g, '\'');
	if (artistRadio == 'Jingle') {
	var urlCoverArt = JINGLE_COVER_ART;
	} else if (artistRadio == 'Tanda'){
	var urlCoverArt = TANDA_COVER_ART;
	} else if (artistRadio == 'Promo'){
	var urlCoverArt = PROMO_COVER_ART;
	} else {
	var urlCoverArt = DEFAULT_COVER_ART;
	}
```

Luego modificaremos esta otra función: `this.refreshCover = function (song = '', artist) {`	
Ahí haremos lo mismo busca
 ```
// Default cover art
 var urlCoverArt = DEFAULT_COVER_ART; 
```
y sustitúyelo por este otro código que es distinto:
```
// Default cover art
const JINGLE_COVER_ART = "img/1.jpg";
const TANDA_COVER_ART = "img/2.jpg";
const PROMO_COVER_ART = "img/3.jpg";
   	
	if (artist == 'Jingle') {
	var urlCoverArt = JINGLE_COVER_ART;
	} else if (artist == 'Tanda'){
	var urlCoverArt = TANDA_COVER_ART;
	} else if (artist == 'Promo'){
	var urlCoverArt = PROMO_COVER_ART;
	} else {
	var urlCoverArt = DEFAULT_COVER_ART;
	}	
```
Con esto tienes solucionado ese tema, puedes poner todos los ELSE IF que quieras y agregar las imágenes que quieras respetando la sintaxis de los comandos.

**Comment by jjbiosca** [comment]
Hola juanamm,

Pues sí, me expreso mejor en castellano, el inglés es con el traductor de Google, jejeje.

Muchísimas gracias por tu ayuda. Este fin de semana modificaré las líneas que me comentas, e incluso antes si puedo, y te comento el resultado.

Y lo de las carátulas con Itunes seguro que es lo del tiempo, porque la mayoría se muestran bien, pero unas pocas fallan y te muestran unas que no tienen nada que ver con el tema.

Muchas gracias de nuevo

**Comment by juanamm** [comment]
Hola @jjbiosca,
No te preocupes, yo hago lo mismo, mi lengua materna es el castellano jaja.
Con respecto a las pocas carátulas que te fallan comprueba los tags exactamente como los muestra la página de Itunes, yo hago lo mismo que tú quito los silencios finales y del comienzo.
En ocasiones he tenido que cambiar el caracter `&` por` ,` o por `/ `incluso otras veces tuve que dejar un espacio en blanco entre diversos autores separados por comas para que la caratula elegida por Itunes fuera la correcta.
Por ejemplo: 
Artista: De La Swing & Nico Ferrada lo cambié por De La Swing / Nico Ferrada
En otras como te comenté, cambié Calvin Harris, Rag'n'Bone Man por Calvin Harris , Rag'n'Bone Man
Es a prueba y error esto jajaja
Espero que tengas éxito, el código que te compartí lo probé antes y funciona, pero si te surge alguna duda me lo haces saber.
Un saludo

**Comment by jjbiosca** [comment]
Una pregunta, ¿las pruebas las haces con el propio reproductor o en alguna página de Itunes?. Te lo digo porque, lo que si empecé a hacer, fue a probar en la página de Apple Music, la misma que me pusiste arriba, los nombres y me buscaba la carátula bien, pero cuando la ponía en directo, el reproductor me mostraba otra distinta.
Un saludo

**Comment by juanamm** [comment]
**First of all, I apologize to the developer and users communicating in English on Github.
This will be the last help in Spanish here.**

@jjbiosca, si te refieres al código que te compartí está probado con el reproductor ya que en ese caso van a ser imágenes particulares tuyas, no de Itunes.
Ahora si te refieres a comparar la caratula que te muestra el reproductor con la de Itunes, lo hago manual en esa página, miro y comparo lo que me muestra el reproductor con lo que sale en la web de Itunes.

También he modificado algunas cosas del script para que la búsqueda de Itunes sea exitosa, he codificado el envío de los caracteres antes de enviarlos, porque algunos caracteres como `&` pueden darte problemas a la hora de encontrar la caratula correcta.
Si bien para ese caracter en concreto el desarrollador hizo una variable que lo reemplaza y codifica bien, luego no la usa a la hora de hacer el GET, no se si fue una omisión, pero yo lo solucioné. 
En la función `this.refreshHistoric = function (info, n) {`
Volví a definir 4 variables, ya que al estar fuera de la función no toman valor y lo hice porque dejando el código original algunas veces el histórico no obtenía la imagen.
El código completo del final de esta función quedó así:
```
var music = info.song.replace(/&apos;/g, '\'');
var songHist = music.replace(/&amp;/g, '&');

var artist = info.artist.replace(/&apos;/g, '\'');
var artistHist = artist.replace(/&amp;/g, '&');
xhttp.open('GET', proxy_URL + itunes_api + artistHist + ' ' + songHist + '&media=music&limit=1.', true);
xhttp.send();
```

**ANTES DE LOS CAMBIOS:**

![itunes_search_bad](https://user-images.githubusercontent.com/48572613/90705666-dfa81700-e269-11ea-94a0-787e7a4130d3.png)

![itunes_cover_bad](https://user-images.githubusercontent.com/48572613/90705435-4c6ee180-e269-11ea-97ec-ba284a11c721.png)

**LUEGO DE LOS CAMBIOS:**

![itunes_search_good](https://user-images.githubusercontent.com/48572613/90705680-e8005200-e269-11ea-9809-55debfcbfd73.png)

![itunes_cover_good](https://user-images.githubusercontent.com/48572613/90705698-ed5d9c80-e269-11ea-8812-ab12e6bc35d7.png)

**Si deseas comparteme un correo eléctronico, porque seguir esta charla particular y en castellano puede que no le guste al desarrollador de esta app o a los usuarios de Github que se comunican en inglés.**
Un saludo

**Comment by jjbiosca** [comment]
Good morning @Juanamm, and sorry that it took so long to answer, but I have been disconnected all this time, in fact I have not even been able to prove what you told me. It's good to be able to continue chatting via email. My email is drjekyll@telefonica.net

A greeting.
