### ISSUE TITLE
ERR_TIMED_OUT

### ISSUE THREAD

**Issue by helio-cg** [gsavio/player-shoutcast-html5#21]
sometimes this error is displayed when trying to access the api. You can play the audio even if the script cannot access the api in the event of an http request error. Because the ip and port data are passed to the player normally

**Comment by mk2box** [comment]
Can you past the error message ?

**Comment by gsavio** [comment]
Hmmm... It seems the problem is on your server. 
I will close this issue, any problem, open a new one.
