### ISSUE TITLE
Nothing Works For Me.

### ISSUE THREAD

**Issue by joeyboli** [gsavio/player-shoutcast-html5#24]
Uploaded It On my cyberpanel powered bt litespeed web server.

index html works well but api get metadata hardly works, all i get it null values

**Comment by joeyboli** [comment]
https://boxradio.me/player/sas/ 


check out here

**Comment by MMS-mk** [comment]
Hello. 
I see in config.js this stream and is down https://tm01.ghanacloud.ga/radio/8170/radio.mp3

**Comment by joeyboli** [comment]
I know but still wasn't working when it was up

**Comment by MMS-mk** [comment]
I see https://boxradio.me/player/sas/api.php?url=https://tm01.ghanacloud.ga/radio/8170/radio.mp3&streamtype=shoutcast&historic=true&next=true&t=1608895503855 work perfectly APi is OK but when i try to your shoutcast server streaming i see https://tm01.ghanacloud.ga/radio/8170 ? What type of streaming server is this its not shoutcast.

**Comment by joeyboli** [comment]
Try This :
https://boxradio.me/player/sas/api.php?url=https://tm01.ghanacloud.ga/radio/8000/radio.mp3&streamtype=icecast&historic=true&next=true&t=1608895503855

This is Icecast. all i get is null values

**Comment by joeyboli** [comment]
Try This too :
http://boxradio.me/player/sas/api.php?url=http://144.91.109.43:8000/radio.mp3&streamtype=icecast&historic=true&next=false&t=1608895503855

**Comment by adoboligh1** [comment]
Figured out. Doesnt Support Icecast-KH
