### ISSUE TITLE
Url stream

### ISSUE THREAD

**Issue by Jsaiao** [gsavio/player-shoutcast-html5#3]
Olá amigo primeiramente muito obrigado por compartilhar seu conhecimento. Parabéns pelo script.

Ele caiu como uma luva para meu projeto Android com webservice e estou utilizando seu player como home na web.

Amigo a minha dúvida seria a seguinte mesmo usando uma url válida a capa do álbum nome do artista e música não é exibido nem mesmo a letra. Como é recepcionado o nome da música? Lembrando que já criei a chave de api do vagalume mas não mostra a letra, em qualquer url que tenha testado somente na url de stream que disponibilizou no exemplo.

**Comment by Jsaiao** [comment]
Existe algum critério? Algo que deixei passar mas sempre que volto a url padrão ela funciona tudo, capa artista música e letra.

**Comment by Jsaiao** [comment]
Desde já agradeço pela ajuda amigo.

**Comment by gsavio** [comment]
Olá, @Jsaiao. Fico feliz que tenha gostado.

Ao colocar a url do seu streaming, você está colocando no formato `http://url:porta` sem `/` no final? E qual a versão do SHOUTCast está usando? Qualquer dúvida estou disponível para ajudar.
