### ISSUE TITLE
New version not work with Icecast

### ISSUE THREAD

**Issue by PoerOne** [gsavio/player-shoutcast-html5#35]
Any suggestion for work with icecast server?
Metadata and album art not working.

**Comment by joeyboli** [comment]
You need two mount points for it to work.

**Comment by bbashy** [comment]
@adoboligh1 I found that too. I just modified the api.php code to allow for 1 mount point.

**Comment by joeyboli** [comment]
wow! please share with me , would love to

**Comment by bbashy** [comment]
Just replace this;
```php
if(is_array($ice_stats["icestats"]["source"])) {
```
with
```php
if (is_array($ice_stats["icestats"]["source"]) && isset($ice_stats["icestats"]["source"][0])) {
```

Line 155: https://github.com/gsavio/player-shoutcast-html5/blob/master/api.php#L155

**Comment by joeyboli** [comment]
Thanks, I'll check it out. Send A PULL request to the developer then😊

**Comment by DirtySkeMe** [comment]
Thanks for the fix

> Just replace this;
> 
> ```
> if(is_array($ice_stats["icestats"]["source"])) {
> ```
> 
> with
> 
> ```
> if (is_array($ice_stats["icestats"]["source"]) && isset($ice_stats["icestats"]["source"][0])) {
> ```
> 
> Line 155: https://github.com/gsavio/player-shoutcast-html5/blob/master/api.php#L155

**Comment by bbashy** [comment]
@adoboligh1 I don't know it well enough to know why it was done like that. It solves my problem and others can use it if they want.

If someone else wants to submit it as a PR, please do.

**Comment by joeyboli** [comment]
I Will.

**Comment by PoerOne** [comment]
Wow.. thanks... I will try try that

**Comment by PoerOne** [comment]
> Just replace this;
> 
> ```
> if(is_array($ice_stats["icestats"]["source"])) {
> ```
> 
> with
> 
> ```
> if (is_array($ice_stats["icestats"]["source"]) && isset($ice_stats["icestats"]["source"][0])) {
> ```
> 
> Line 155: https://github.com/gsavio/player-shoutcast-html5/blob/master/api.php#L155

Thanks @bbashy !!! It works!!!
