### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by xilega** [gsavio/player-shoutcast-html5#4]
Antes de mais, excelente player! Obrigado pelo trabalho e por disponibilizar.

A minha questão é a seguinte.
Existe forma de através do browser do smartphone o audio começar com autoplay?
Como está, o utilizador é forçado a clicar no botão PLAY.

Mais uma vez obrigado.

**Comment by gsavio** [comment]
Fico feliz que tenha gostado!

Respondendo sua dúvida, não tem mais como isso acontecer pois os navegadores atualmente exigem uma interação do usuário antes de executar alguma ação.

Qualquer dúvida, estamos aí.

**Comment by xilega** [comment]
Obrigado Guilherme, também estive a pesquisar e de facto não existir solução.
