### ISSUE TITLE
Add support for Icecast Servers

### ISSUE THREAD

**Issue by andreas5232** [gsavio/player-shoutcast-html5#6]
I just stumbled upon this pretty neat piece of software and found it quite cool!
Unfortunately I'm currently running our radio stream using an Icecast Server, so I had to do several adjustments to the original code in order to also support Icecast. 

What I got running:
- Icecast audio stream
- Current Song details
- Song history (with local file cache)

As soon as I got time, I'll try to implement the Icecast support as a simple config switch and do a pull request.

**Comment by gsavio** [comment]
I'm glad that you liked and want to improve it. For now, I also don't have much time to improvements, but If you need help, as far as possible, I'll try to help.

Best regards!
