### ISSUE TITLE
Add dedicated configuration file 

### ISSUE THREAD

**Issue by andreas5232** [gsavio/player-shoutcast-html5#7]
Currently all configuration must be done within the `script.js` file. To make things easier and also allow to change HTML contents like meta-tags via config, it would be cool, to have all configuration at the same place for both PHP and JavaScript.

In the end, I want to be able to update my running  player installation using the recent git version without any manual changes to the code. Just keeping my local configuration file and maybe the station logo.

**Comment by gsavio** [comment]
Hi @andreas5232 

It's a good idea, and sorry for the delay in reading your suggestion.

In the next update, I will implement it. Thanks for your help.
