### ISSUE TITLE
can't access meta data

### ISSUE THREAD

**Issue by hiro-rocks** [gsavio/player-shoutcast-html5#9]
Hello, thank you for sharing wonderful player. 

But I'm having issue not showing meta data at all (now playing and previous ones). I can hear my stream so url setting should be fine. How to solve this?

I'm using shoutcast v2.  I don't get both api keys yet. My stream url is http://freebird.ddns.net:8050 
AAC+ 64k
player url : http://www.freebirdradio.net/64kplayer/

Thank you.

**Comment by jlrodriguezdev** [comment]
The same issue 
Music play, meta data is empty

**Comment by FabioTech** [comment]
the streaming link has to be with HTTPS, google is blocking: http://freebird.ddns.net:8050.

see mine is working all normal: https://fabiotech.github.io/radio/

**Comment by gsavio** [comment]
Hi @hiro-rocks and @jose2016 

It seems your api.php file has something wrong on line 42. Try to clone again and see if it resolve.

Any questions, as soon as possible I will help. 😃

**Comment by hiro-rocks** [comment]
Thanks for reply. I refreshed all files, now it seems working fine. Thank you!

**Comment by juanamm** [comment]
> 
> see mine is working all normal: https://fabiotech.github.io/radio/

Your site no longer works:
https://s7.gifyu.com/images/no_work1.png

**Comment by adukale** [comment]
@gsavio 
I am not getting any meta data and song names. Here: http://bharatiysangeet.com/listen1/
I have AzuraCast installed. Any help is much appreciated.

Thank You
